# Generated by Django 3.0.8 on 2020-07-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mBlogApp', '0002_auto_20200710_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author_id',
            new_name='author',
        ),
    ]
