# Generated by Django 3.0.8 on 2020-07-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mBlogApp', '0005_auto_20200722_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='albumart',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
