# Generated by Django 3.0.8 on 2020-07-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mBlogApp', '0007_auto_20200723_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='spotifylink',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
