# Generated by Django 3.0.8 on 2020-07-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mBlogApp', '0008_post_spotifylink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='spotifylink',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
