# Generated by Django 3.0.8 on 2020-07-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mBlogApp', '0009_auto_20200723_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upvotes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
