# Generated by Django 3.0.8 on 2020-08-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mBlogApp', '0012_auto_20200806_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='albumart',
            field=models.ImageField(blank=True, default='album_art/default.jpg', null=True, upload_to='album_art'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(default='profile_photos/default.jpg', upload_to='profile_photos'),
        ),
    ]
