# Generated by Django 3.0.8 on 2020-08-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mBlogApp', '0013_auto_20200806_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
