# Generated by Django 3.0.8 on 2020-08-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mBlogApp', '0014_genre_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='changed_profile_photo',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
